services:
  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=daily_develop
    ports:
      - "5433:5432"
  keycloak:
    image: 'quay.io/keycloak/keycloak:20.0.2'
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/daily-realm.json:/opt/keycloak/data/import/daily-realm.json
    ports:
      - "8081:8080"
  redis:
    image: 'redis:latest'
    container_name: redis
    ports:
      - "6379:6379"
  email:
    image: 'mailhog/mailhog'
    container_name: email
    ports:
      - "8025:8025"
      - "1025:1025"