services:
  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=daily_develop
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
  keycloak:
    image: 'quay.io/keycloak/keycloak:latest'
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
      - --import-realm
      - --health-enabled=true
    volumes:
      - ./keycloak/daily-realm.json:/opt/keycloak/data/import/daily-realm.json
    ports:
      - "8081:8080"
    healthcheck:
      test: "{ printf >&3 'GET /realms/daily/.well-known/openid-configuration HTTP/1.0\r\nHost: localhost\r\n\r\n'; cat <&3; } 3<>/dev/tcp/localhost/8080 | head -1 | grep 200"
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 3
  redis:
    image: 'redis:latest'
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
  email:
    image: 'corpusops/mailhog:latest'
    container_name: email
    ports:
      - "8025:8025"
      - "1025:1025"
    healthcheck:
      test: "curl -f localhost:8025/api/v2/messages"
      interval: 10s
      timeout: 5s
      retries: 3