services:
  daily:
    image: 'daily:latest'
    container_name: daily
    build:
      context: .
      dockerfile: dockerfile/daily-Dockerfile
    depends_on:
      - db
    environment:
      - GOOGLE_OAUTH2_CLIENT_ID=<google-client-id>
      - GOOGLE_OAUTH2_CLIENT_SECRET=<google-client-secret>
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/daily_develop
    ports:
      - "8080:8080"
  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=daily_develop